project:
  type: website

execute: 
  freeze: auto
website:
  title: "Soumya M."
  favicon: /img/Sm_logo.png
  search: true
  navbar:
    # logo: /img/Sm_logo.png

    left:
      - href: index.qmd
        text: Home
      - text: Projects
        href: projects.qmd
      - text: Blog
        href: blog.qmd
      - text: Useful
        href: useful.qmd
      - text: CV
      - text: Gallery
        href: gallery.qmd
    
    right: 
      - icon: linkedin
        href: https://www.linkedin.com/in/soumya-mukhopadhyay-947721165/
      - icon: github
        href: https://github.com/Newmood
  
  page-footer: 
    border: true
    left: "&#169; 2024 Soumya Mukhopadhyay"
    right: "made with [Quarto](https://quarto.org/)"

format:
  html:
    theme: 
      light: [flatly, light.scss]
      dark: darkly
    # css: styles.css
    toc: false
    pagetitle: "Soumya M | {{< meta title >}}"